### PR TITLE
Adding Support for disabled

### PR DESCRIPTION
**Pull request by willcode4food**
The ability to specify whether an input is disabled or not from the JSON schema is an important factor a project I am working.  Let me know what you think.

### CODE REVIEW

**Comment by ismaelga** [comment]
Thanks!
This should go in the x-hint property because it's not defining the schema, it's just a hint for the form.

**Comment by willcode4food** [comment]
Sounds, good.  I'll refactor.  Also, I was thinking I need to make this available to the other form elements.  I'll keep working on it.

Thanks for the feedback.

**Comment by willcode4food** [comment]
Ok so the disabled field is now moved to the x-hints -> form section and available in the checkbox and select form elements

**Comment by ismaelga** [comment]
Thanks

**Pull request merged**
