### PR TITLE
Added new unit test for dependant properties

### PR DESCRIPTION
**Pull request by bananafunctor**
Unfortunately it seems this new unit test will not pass with the current revision, indeed it seems the form will not purge non-rendered values when updating state in `Form.SetValue`. Thus this will lead to old values remaining in state even when submitting.

### CODE REVIEW

**Comment by ismaelga** [comment]
I've noticed this before. It would really be a nice thing to have: Remove properties not in the schema. Shouldn't be that hard actually. Do you wan't to give it a try?

Thanks for adding the test. :heart:  This will make it easier to fix it.

**Comment by bananafunctor** [comment]
I have been looking at it, the problem is the way that the form updates it's internal state where each child component will sequentially update the state of the form on it's `onChange` event and that value is then merged into the new state. There isn't an easy fix as far as I know, I made a "pseudo fix" where I basically checked the schema for differences in "sub properties" of property "foo" vs new property "bar", but that is sort of a convoluted fix.

**Comment by haf** [comment]
@ismaelga Are you up for merging this? Can we do anything to help you merge it?

**Comment by ismaelga** [comment]
@bananafunctor could you send your "pseudo fix"? It would be great to keep all the data while editing the form but only output for the current subschema.

**Comment by bananafunctor** [comment]
@ismaelga Could we go ahead and merge this PR first? The fix that I have is not very robust, and I'd like to refine it a bit more before I commit it.

**Comment by haf** [comment]
Thank you.

**Pull request merged**
