### PR TITLE
array and object handling closer to ie support

### PR DESCRIPTION
**Pull request by lapponiandevil**
I am still getting some weird double loading in IE, which I don't get in Firefox. Inital load of object still throws in some prototype property (find).
A penny for your thoughts.

### CODE REVIEW

**Comment by ismaelga** [comment]
Thanks for the PR! I will probably pull it tomorrow and try to make it fully work on IE. It would be nice if you could test it after, because I don't have windows on my machine.

**Comment by lapponiandevil** [comment]
I stumbled on a root and fell into a hole, otherwise I would have been on the case. Some unit tests would be a good start, to make sure we don't break the simplest cases...

**Comment by haf** [comment]
There are unit tests that can be extended now!

**Comment by ismaelga** [comment]
What version of IE it does not support?

**Comment by lapponiandevil** [comment]
I tested it with Win 8.1, IE 11.
As Microsoft will end support for all but the latest browser on each platform, I don't think that there is need for this project to look at the other ones either.

**Pull request closed without merging**
