### PR TITLE
hidden fields support

### PR DESCRIPTION
**Pull request by willcode4food**
Adding hidden fields to x-hints -> form

### CODE REVIEW

**Comment by willcode4food** [comment]
Submitted this about a week ago.  Any thoughts?

**Comment by ismaelga** [comment]
It would be better without the merges. But merged anyway. Thanks!

**Comment by willcode4food** [comment]
Noted.  Sorry for the inconvenience.  Thanks for responding

**Comment by ismaelga** [comment]
You should have done rebase instead of merge for a PR. Makes the history cleaner.
Not a big deal really

**Pull request merged**
